<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Orders;
use AppBundle\Entity\User;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrderByUser($idStatus)
    {
        $qb = $this->createQueryBuilder('o');

        $qb->select('o.id')
            ->join(User::class,'u', 'WITH','u.id_order = id')
            ->where('o.status_order_id = :id')
            ->setParameter('id',  $idStatus);

        $query = $qb->getQuery();

        $result = $query->getResult();


        return $result;
    }
}


