<?php

namespace AppBundle\Repository;

/**
 * Status_ordersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Status_ordersRepository extends \Doctrine\ORM\EntityRepository
{
}
