<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Orders;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchOrderByUser($idUser)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->select('o.id')
            ->join(Orders::class,'o','WITH','orders_id = o.id')
            ->where('u.id = :id')
            ->setParameter('id',$idUser);

        $query = $qb->getQuery();

        $result = $query->getResult();

        return $result;

    }
}
