<?php

namespace AppBundle\Repository;

/**
 * Users_StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users_StatusRepository extends \Doctrine\ORM\EntityRepository
{
}
